PARSE_APP_ID: "DLKLmRXs1s02U9aX9oOx70pdkliCgSvvmueLsxnm"
PARSE_REST_API_KEY: "RnbfupaB0nV61jFqoL4kzvigjVbrMFY55EBVPSHZ"
AWS_ACCESS_KEY_ID: "AKIAI75SLGKUTBAHCSPA"
AWS_SECRET_ACCESS_KEY: "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"
SCHEDULER_ENABLE: "false"