require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe M::ProfilesController do

  # This should return the minimal set of attributes required to create a valid
  # M::Profile. As you add validations to M::Profile, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all m_profiles as @m_profiles" do
      profile = M::Profile.create! valid_attributes
      get :index
      assigns(:m_profiles).should eq([profile])
    end
  end

  describe "GET show" do
    it "assigns the requested m_profile as @m_profile" do
      profile = M::Profile.create! valid_attributes
      get :show, :id => profile.id.to_s
      assigns(:m_profile).should eq(profile)
    end
  end

  describe "GET new" do
    it "assigns a new m_profile as @m_profile" do
      get :new
      assigns(:m_profile).should be_a_new(M::Profile)
    end
  end

  describe "GET edit" do
    it "assigns the requested m_profile as @m_profile" do
      profile = M::Profile.create! valid_attributes
      get :edit, :id => profile.id.to_s
      assigns(:m_profile).should eq(profile)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new M::Profile" do
        expect {
          post :create, :m_profile => valid_attributes
        }.to change(M::Profile, :count).by(1)
      end

      it "assigns a newly created m_profile as @m_profile" do
        post :create, :m_profile => valid_attributes
        assigns(:m_profile).should be_a(M::Profile)
        assigns(:m_profile).should be_persisted
      end

      it "redirects to the created m_profile" do
        post :create, :m_profile => valid_attributes
        response.should redirect_to(M::Profile.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved m_profile as @m_profile" do
        # Trigger the behavior that occurs when invalid params are submitted
        M::Profile.any_instance.stub(:save).and_return(false)
        post :create, :m_profile => {}
        assigns(:m_profile).should be_a_new(M::Profile)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        M::Profile.any_instance.stub(:save).and_return(false)
        post :create, :m_profile => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested m_profile" do
        profile = M::Profile.create! valid_attributes
        # Assuming there are no other m_profiles in the database, this
        # specifies that the M::Profile created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        M::Profile.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => profile.id, :m_profile => {'these' => 'params'}
      end

      it "assigns the requested m_profile as @m_profile" do
        profile = M::Profile.create! valid_attributes
        put :update, :id => profile.id, :m_profile => valid_attributes
        assigns(:m_profile).should eq(profile)
      end

      it "redirects to the m_profile" do
        profile = M::Profile.create! valid_attributes
        put :update, :id => profile.id, :m_profile => valid_attributes
        response.should redirect_to(profile)
      end
    end

    describe "with invalid params" do
      it "assigns the m_profile as @m_profile" do
        profile = M::Profile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        M::Profile.any_instance.stub(:save).and_return(false)
        put :update, :id => profile.id.to_s, :m_profile => {}
        assigns(:m_profile).should eq(profile)
      end

      it "re-renders the 'edit' template" do
        profile = M::Profile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        M::Profile.any_instance.stub(:save).and_return(false)
        put :update, :id => profile.id.to_s, :m_profile => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested m_profile" do
      profile = M::Profile.create! valid_attributes
      expect {
        delete :destroy, :id => profile.id.to_s
      }.to change(M::Profile, :count).by(-1)
    end

    it "redirects to the m_profiles list" do
      profile = M::Profile.create! valid_attributes
      delete :destroy, :id => profile.id.to_s
      response.should redirect_to(m_profiles_url)
    end
  end

end
